<?php

use Illuminate\Database\Seeder;

class CitySeeder7 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('cities')->insert([ 'geoname_id'=> '3513261', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'SX', 'country_name'=> 'Sint Maarten', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Saunders', 'metro_code'=> '', 'time_zone'=> 'America/Lower_Princes', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3513392', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'SX', 'country_name'=> 'Sint Maarten', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Philipsburg', 'metro_code'=> '', 'time_zone'=> 'America/Lower_Princes', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3513794', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'SX', 'country_name'=> 'Sint Maarten', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Cul de Sac', 'metro_code'=> '', 'time_zone'=> 'America/Lower_Princes', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573522', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SIP', 'subdivision_1_name'=> 'Siparia', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Woodland', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573523', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'POS', 'subdivision_1_name'=> 'Port of Spain', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Woodbrook', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573529', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PRT', 'subdivision_1_name'=> 'Princes Town', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Williamsville', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573547', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SFO', 'subdivision_1_name'=> 'San Fernando', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Vistabella', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573550', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SFO', 'subdivision_1_name'=> 'San Fernando', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Victoria', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573557', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Valsayn', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573560', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SGE', 'subdivision_1_name'=> 'Sangre Grande', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Valencia', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573576', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Tunapuna', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573591', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> '', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573606', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TOB', 'subdivision_1_name'=> 'Tobago', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> '', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573650', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Tabaquite', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573668', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SIP', 'subdivision_1_name'=> 'Siparia', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'South Oropouche', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573681', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SIP', 'subdivision_1_name'=> 'Siparia', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Siparia', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573703', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TOB', 'subdivision_1_name'=> 'Tobago', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Scarborough', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573715', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SJL', 'subdivision_1_name'=> 'San Juan/Laventille', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Santa Cruz', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573727', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SJL', 'subdivision_1_name'=> 'San Juan/Laventille', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'San Juan', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573732', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SGE', 'subdivision_1_name'=> 'Sangre Grande', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Sangre Grande', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573738', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SFO', 'subdivision_1_name'=> 'San Fernando', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'San Fernando', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573773', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Saint Joseph', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573779', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'POS', 'subdivision_1_name'=> 'Port of Spain', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Saint James', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573781', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Saint Helena', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573794', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'POS', 'subdivision_1_name'=> 'Port of Spain', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Saint Clair', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573796', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Saint Augustine', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573819', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TOB', 'subdivision_1_name'=> 'Tobago', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Roxborough', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573840', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'MRC', 'subdivision_1_name'=> 'Mayaro', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Rio Claro', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573850', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PRT', 'subdivision_1_name'=> 'Princes Town', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Reform', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573882', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PRT', 'subdivision_1_name'=> 'Princes Town', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Princes Town', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573890', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'POS', 'subdivision_1_name'=> 'Port of Spain', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Port of Spain', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573899', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PTF', 'subdivision_1_name'=> 'Point Fortin', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Point Fortin', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573903', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TOB', 'subdivision_1_name'=> 'Tobago', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Plymouth', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573918', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PRT', 'subdivision_1_name'=> 'Princes Town', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Piparo', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573932', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Piarco', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573935', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'DMN', 'subdivision_1_name'=> 'Diego Martin', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Petit Valley', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573957', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SJL', 'subdivision_1_name'=> 'San Juan/Laventille', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Petit Bourg', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573965', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PED', 'subdivision_1_name'=> 'Penal/Debe', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Penal', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3573995', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SIP', 'subdivision_1_name'=> 'Siparia', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Palo Seco', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574038', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PRT', 'subdivision_1_name'=> 'Princes Town', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'New Grant', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574081', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SJL', 'subdivision_1_name'=> 'San Juan/Laventille', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Morvant', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574184', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'DMN', 'subdivision_1_name'=> 'Diego Martin', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Maraval', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574194', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SFO', 'subdivision_1_name'=> 'San Fernando', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Marabella', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574260', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SIP', 'subdivision_1_name'=> 'Siparia', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Los Bajos', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574309', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SJL', 'subdivision_1_name'=> 'San Juan/Laventille', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Laventille', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574353', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SIP', 'subdivision_1_name'=> 'Siparia', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'La Brea', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574363', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Kelly Village', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574472', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SIP', 'subdivision_1_name'=> 'Siparia', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Granville', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574497', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Gran Couva', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574517', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TOB', 'subdivision_1_name'=> 'Tobago', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Glamorgan', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574524', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Gasparillo', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574536', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SIP', 'subdivision_1_name'=> 'Siparia', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Fyzabad', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574545', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Freeport', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574565', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TOB', 'subdivision_1_name'=> 'Tobago', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Florida', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574604', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'El Dorado', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574623', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Dowe', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574636', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'DMN', 'subdivision_1_name'=> 'Diego Martin', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Diego Martin', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574659', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PED', 'subdivision_1_name'=> 'Penal/Debe', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Debe', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574665', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'D\'Abadie', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574671', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Curepe', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574680', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CHA', 'subdivision_1_name'=> 'Chaguanas', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Cunupia', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574724', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Couva', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574754', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PED', 'subdivision_1_name'=> 'Penal/Debe', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Golconda', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574773', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Claxton Bay', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574794', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Chase Village', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574810', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CHA', 'subdivision_1_name'=> 'Chaguanas', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Chaguanas', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574848', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Caroni', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574855', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'DMN', 'subdivision_1_name'=> 'Diego Martin', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Carenage', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574866', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Carapichaima', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574874', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PTF', 'subdivision_1_name'=> 'Point Fortin', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Cap-de-Ville', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574895', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'CTT', 'subdivision_1_name'=> 'Couva-Tabaquite-Talparo', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'California', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3574991', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'MRC', 'subdivision_1_name'=> 'Mayaro', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Biche', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575010', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'PED', 'subdivision_1_name'=> 'Penal/Debe', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Barrackpore', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575012', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SJL', 'subdivision_1_name'=> 'San Juan/Laventille', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Barataria', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575039', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Arouca', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575051', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'ARI', 'subdivision_1_name'=> 'Borough of Arima', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Arima', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575115', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'15', 'subdivision_1_name'=> 'Trinity Palmetto Point', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Trinity', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575126', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'6', 'subdivision_1_name'=> 'Saint John Capesterre', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Tabernacle', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575156', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'2', 'subdivision_1_name'=> 'Saint Anne Sandy Point', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Sandy Point Town', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575174', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> '', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575240', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'13', 'subdivision_1_name'=> 'Middle Island', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Old Road Town', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575251', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'1', 'subdivision_1_name'=> 'Christ Church Nichola Town', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Nicola Town', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575254', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'9', 'subdivision_1_name'=> 'Saint Paul Capesterre', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Newton Ground', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575261', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'5', 'subdivision_1_name'=> 'Saint James Windward', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Newcastle', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575284', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'11', 'subdivision_1_name'=> 'Saint Peter Basseterre', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Monkey Hill', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575288', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'1', 'subdivision_1_name'=> 'Christ Church Nichola Town', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Molineux', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575292', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'13', 'subdivision_1_name'=> 'Middle Island', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Middle Island', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575344', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'12', 'subdivision_1_name'=> 'Saint Thomas Lowland', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Jessup', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575403', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'4', 'subdivision_1_name'=> 'Saint George Gingerland', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Gingerland', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575441', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'6', 'subdivision_1_name'=> 'Saint John Capesterre', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Dieppe Bay Town', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575458', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'12', 'subdivision_1_name'=> 'Saint Thomas Lowland', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Cotton Ground', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575479', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'10', 'subdivision_1_name'=> 'Saint Paul Charlestown', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Charlestown', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575487', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'8', 'subdivision_1_name'=> 'Saint Mary Cayon', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Cayon', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575544', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'7', 'subdivision_1_name'=> 'Saint John Figtree', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Beaumont', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3575551', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'KN', 'country_name'=> 'St Kitts and Nevis', 'subdivision_1_iso_code'=>'3', 'subdivision_1_name'=> 'Saint George Basseterre', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Basseterre', 'metro_code'=> '', 'time_zone'=> 'America/St_Kitts', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3576916', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TC', 'country_name'=> 'Turks and Caicos Islands', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> '', 'metro_code'=> '', 'time_zone'=> 'America/Grand_Turk', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3576994', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TC', 'country_name'=> 'Turks and Caicos Islands', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Cockburn Town', 'metro_code'=> '', 'time_zone'=> 'America/Grand_Turk', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577043', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TC', 'country_name'=> 'Turks and Caicos Islands', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Blue Hills Settlements', 'metro_code'=> '', 'time_zone'=> 'America/Grand_Turk', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577054', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TC', 'country_name'=> 'Turks and Caicos Islands', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Balfour Town', 'metro_code'=> '', 'time_zone'=> 'America/Grand_Turk', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577795', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VC', 'country_name'=> 'Saint Vincent and the Grenadines', 'subdivision_1_iso_code'=>'6', 'subdivision_1_name'=> 'Grenadines', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Union', 'metro_code'=> '', 'time_zone'=> 'America/St_Vincent', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577815', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VC', 'country_name'=> 'Saint Vincent and the Grenadines', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> '', 'metro_code'=> '', 'time_zone'=> 'America/St_Vincent', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577825', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VC', 'country_name'=> 'Saint Vincent and the Grenadines', 'subdivision_1_iso_code'=>'5', 'subdivision_1_name'=> 'Parish of Saint Patrick', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Rutland Vale', 'metro_code'=> '', 'time_zone'=> 'America/St_Vincent', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577839', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VC', 'country_name'=> 'Saint Vincent and the Grenadines', 'subdivision_1_iso_code'=>'2', 'subdivision_1_name'=> 'Parish of Saint Andrew', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Questelles', 'metro_code'=> '', 'time_zone'=> 'America/St_Vincent', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577844', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VC', 'country_name'=> 'Saint Vincent and the Grenadines', 'subdivision_1_iso_code'=>'6', 'subdivision_1_name'=> 'Grenadines', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Port Elizabeth', 'metro_code'=> '', 'time_zone'=> 'America/St_Vincent', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577873', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VC', 'country_name'=> 'Saint Vincent and the Grenadines', 'subdivision_1_iso_code'=>'1', 'subdivision_1_name'=> 'Parish of Charlotte', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Mesopotamia', 'metro_code'=> '', 'time_zone'=> 'America/St_Vincent', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577887', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VC', 'country_name'=> 'Saint Vincent and the Grenadines', 'subdivision_1_iso_code'=>'4', 'subdivision_1_name'=> 'Parish of Saint George', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Kingstown', 'metro_code'=> '', 'time_zone'=> 'America/St_Vincent', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577900', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VC', 'country_name'=> 'Saint Vincent and the Grenadines', 'subdivision_1_iso_code'=>'1', 'subdivision_1_name'=> 'Parish of Charlotte', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Georgetown', 'metro_code'=> '', 'time_zone'=> 'America/St_Vincent', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '3577933', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VC', 'country_name'=> 'Saint Vincent and the Grenadines', 'subdivision_1_iso_code'=>'3', 'subdivision_1_name'=> 'Parish of Saint David', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Chateaubelair', 'metro_code'=> '', 'time_zone'=> 'America/St_Vincent', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '4795467', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VI', 'country_name'=> 'U.S. Virgin Islands', 'subdivision_1_iso_code'=>'T', 'subdivision_1_name'=> 'Saint Thomas Island', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Charlotte Amalie', 'metro_code'=> '', 'time_zone'=> 'America/St_Thomas', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '4795479', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VI', 'country_name'=> 'U.S. Virgin Islands', 'subdivision_1_iso_code'=>'C', 'subdivision_1_name'=> 'Saint Croix Island', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Christiansted', 'metro_code'=> '', 'time_zone'=> 'America/St_Thomas', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '4795577', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VI', 'country_name'=> 'U.S. Virgin Islands', 'subdivision_1_iso_code'=>'J', 'subdivision_1_name'=> 'Saint John Island', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Cruz Bay', 'metro_code'=> '', 'time_zone'=> 'America/St_Thomas', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '4795761', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VI', 'country_name'=> 'U.S. Virgin Islands', 'subdivision_1_iso_code'=>'C', 'subdivision_1_name'=> 'Saint Croix Island', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Frederiksted', 'metro_code'=> '', 'time_zone'=> 'America/St_Thomas', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '4795976', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VI', 'country_name'=> 'U.S. Virgin Islands', 'subdivision_1_iso_code'=>'C', 'subdivision_1_name'=> 'Saint Croix Island', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Kingshill', 'metro_code'=> '', 'time_zone'=> 'America/St_Thomas', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '4796512', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VI', 'country_name'=> 'U.S. Virgin Islands', 'subdivision_1_iso_code'=>'C', 'subdivision_1_name'=> 'Saint Croix Island', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'St Croix', 'metro_code'=> '', 'time_zone'=> 'America/St_Thomas', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '4796775', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'VI', 'country_name'=> 'U.S. Virgin Islands', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> '', 'metro_code'=> '', 'time_zone'=> 'America/St_Thomas', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '6985404', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'SX', 'country_name'=> 'Sint Maarten', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Dutch Quarter', 'metro_code'=> '', 'time_zone'=> 'America/Lower_Princes', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '6985411', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'SX', 'country_name'=> 'Sint Maarten', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Koolbaai', 'metro_code'=> '', 'time_zone'=> 'America/Lower_Princes', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '7521947', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'TUP', 'subdivision_1_name'=> 'Tunapuna/Piarco', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> '', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '7609695', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'SX', 'country_name'=> 'Sint Maarten', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> '', 'metro_code'=> '', 'time_zone'=> 'America/Lower_Princes', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '8709804', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'DMN', 'subdivision_1_name'=> 'Diego Martin', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Goodwood Park', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '8710030', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'SFO', 'subdivision_1_name'=> 'San Fernando', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'La Romain', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '10793921', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'SX', 'country_name'=> 'Sint Maarten', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Cupecoy', 'metro_code'=> '', 'time_zone'=> 'America/Lower_Princes', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '11468245', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TT', 'country_name'=> 'Trinidad and Tobago', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Trincity', 'metro_code'=> '', 'time_zone'=> 'America/Port_of_Spain', 'is_in_european_union'=> false, ]);
        DB::table('cities')->insert([ 'geoname_id'=> '11703857', 'locale_code'=> 'en', 'continent_code'=> 'NA', 'continent_name'=> 'North America', 'country_iso_code'=> 'TC', 'country_name'=> 'Turks and Caicos Islands', 'subdivision_1_iso_code'=>'', 'subdivision_1_name'=> '', 'subdivision_2_iso_code'=>'', 'subdivision_2_name'=> '', 'city_name'=> 'Providenciales', 'metro_code'=> '', 'time_zone'=> 'America/Grand_Turk', 'is_in_european_union'=> false, ]);

    }
}
